const sampleProducts = [
  {
    productId: "P-001",
    name: "Laptop",
    category: "Electronics",
    company: "Dell",
    price: 1200,
    quantity: 10,
    supplier: "Tech Supplier",
    description: "High-performance laptop",
  },
  {
    productId: "P-002",
    name: "Mouse",
    category: "Accessories",
    company: "Logitech",
    price: 20,
    quantity: 2,
    supplier: "Tech Supplier",
    description: "Wireless mouse",
  },
  {
    productId: "P-003",
    name: "Keyboard",
    category: "Accessories",
    company: "Logitech",
    price: 30,
    quantity: 0,
    supplier: "Tech Supplier",
    description: "Mechanical keyboard",
  },
  {
    productId: "P-004",
    name: "Smartphone",
    category: "Electronics",
    company: "Samsung",
    price: 900,
    quantity: 8,
    supplier: "Mobile Hub",
    description: "Latest Android smartphone",
  },
  {
    productId: "P-005",
    name: "Headphones",
    category: "Audio",
    company: "Sony",
    price: 150,
    quantity: 5,
    supplier: "Sound World",
    description: "Noise-cancelling over-ear headphones",
  },
  {
    productId: "P-006",
    name: "Smartwatch",
    category: "Wearables",
    company: "Apple",
    price: 400,
    quantity: 4,
    supplier: "Tech Supplier",
    description: "Series 8 smartwatch with fitness tracking",
  },
  {
    productId: "P-007",
    name: "USB Cable",
    category: "Accessories",
    company: "Anker",
    price: 10,
    quantity: 25,
    supplier: "Cable Shop",
    description: "Fast charging Type-C cable",
  },
  {
    productId: "P-008",
    name: "Monitor",
    category: "Electronics",
    company: "HP",
    price: 250,
    quantity: 6,
    supplier: "Display Tech",
    description: "27-inch Full HD LED monitor",
  },
  {
    productId: "P-009",
    name: "Printer",
    category: "Office Equipment",
    company: "Canon",
    price: 350,
    quantity: 3,
    supplier: "Office Supply Co.",
    description: "All-in-one wireless color printer",
  },
  {
    productId: "P-010",
    name: "External Hard Drive",
    category: "Storage",
    company: "Seagate",
    price: 100,
    quantity: 7,
    supplier: "Tech Supplier",
    description: "1TB USB 3.0 external hard drive",
  },
];



export default sampleProducts;